## Loops
  - Multiple ways to go about loops or iterators across languages
  - We'll be going over for and while loops

In [10]:
import numpy as np

n = 2
twod = np.random.random((n, n))
count = 0
for i in range(0, n):
    for j in range(0,n):
        print(f'i,j: {i},{j}:\n {twod[i,j]}')
        count += 1

print(f'Count: {count}')

i,j: 0,0:
 0.48750187295823366
i,j: 0,1:
 0.9077176734129314
i,j: 1,0:
 0.21725757564495873
i,j: 1,1:
 0.17869194733822813
Count: 4


## Challenge
Print the odd numbers 2D array of size $n \times n$ in reverse using array-indexing syntax ie array\[index_1\]\[index_2\]
- Hint: Using the range function works, you just have to change two lines of code from the previous example
- [Range Python Docs](https://docs.python.org/3/library/functions.html#func-range)

In [23]:
## Solution
import numpy as np

n = 4
twod = np.random.random((n, n))
count = 0
print(twod)
# print(f'array:\n{twod}')
for i in range(n-1, -1, -1):
    if (i % 2) != 0:
        continue
    for j in range(n-1, -1, -1):
        if (j % 2) != 0:
           continue
        print(f'i,j: {i},{j}:\n {twod[i,j]}')
        count += 1

print(f'Count: {count}')

[[0.54641203 0.63265213 0.69823858 0.34581273]
 [0.76176635 0.78613158 0.43316514 0.29159059]
 [0.17263117 0.69479893 0.44257255 0.87066134]
 [0.50802832 0.62007717 0.38145426 0.20391151]]
i,j: 2,2:
 0.4425725513148684
i,j: 2,0:
 0.17263116992522187
i,j: 0,2:
 0.6982385802657936
i,j: 0,0:
 0.5464120261286428
Count: 4


## While loops
- Form: while CONDITION: {procedure}
- Goes into while loop if condition is true, at the end of while
indent it goes back to the check the condition. If the condition is still true then it goes back into the loop, if condition is false then it jumps to the first line after the loop

In [7]:
i = 0

print(f"While loop")
while i < 5:
    print(f'i: {i}', end=', ')
    i += 1
# this is the same as
print(f"\nfor loop")
for i in range(5):
    print(f'i: {i}', end=', ')


While loop
i: 0, i: 1, i: 2, i: 3, i: 4, 
for loop
i: 0, i: 1, i: 2, i: 3, i: 4, 